### ISSUE TITLE
Open data Nice indispo sur transport.data.gouv.fr

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/gtfs#19]
https://transport.data.gouv.fr/datasets/export-quotidien-au-format-gtfs-du-reseau-de-transport-lignes-d-azur

**Comment by coumbsek** [comment]
Le fichier GTFSExport.zip est en effet annoncé comme ressource indisponible et mène à une page 404 mais en passant par les ressources historisées le dernier upload a bien été validé et est accessible en téléchargement. Il l'est également directement sur le site opendata de la métropole de Nice.

D'après un agent de la métropole c'est un problème du côté de chez transport.data. Pour transport.data c'est la métropole qui met un lien à dispo en http au lieu de https (réponse du 03/07/2024). Espérons que ça sera rapidement résolut

**Comment by Jean-BaptisteC** [comment]
Nice à été intégré
