### ISSUE TITLE
La route /stopTimes est beaucoup trop grosse

### ISSUE THREAD

**Issue by laem** [cartesapp/gtfs#5]
- [x] Déjà, on pourrait ne pas envoyer les valeurs null ou undefined dans stops et stopTimes. 
- [x] On pourrait aussi les transformer en tableaux. 

Aussi, ne pas envoyer les shapes, ça peut être fait via une requête supplémentaire.

**Comment by laem** [comment]
![image](https://github.com/user-attachments/assets/8f06a6cc-feed-47ab-affa-d8073d2cb592)

**Comment by laem** [comment]
Je ferme, la suite dans https://github.com/laem/cartes/pull/626

**Comment by Jean-BaptisteC** [comment]
Le ticket n'est pas fermé 😉
