### ISSUE TITLE
GTFS Saint-Étienne merde 😅

### ISSUE THREAD

**Issue by laem** [cartesapp/gtfs#8]
![Capture d’écran 2024-06-28 à 22 06 48](https://github.com/laem/cartes/assets/1177762/25325de2-d133-4d57-81b7-d1ddbbabdd18)

**Comment by Jean-BaptisteC** [comment]
Le Stan de Nancy est aussi à désactiver
<img src="https://github.com/user-attachments/assets/4f0681b7-3a65-4242-96ae-1d2b22444439" height=300 />

**Comment by Jean-BaptisteC** [comment]
Je ferais une PR pour réactiver Nancy prochainement.
Je ne comprends que la plateforme transport data gouv ne contrôle pas ce genre de choses.

**Comment by laem** [comment]
>  Je ne comprends que la plateforme transport data gouv ne contrôle pas ce genre de choses.

Chaque GTFS est un export de BDD en silo. Le problème vient de là. La norme GTFS aurait du prévoir l'usage et demander autant que possible à ce que chaque jeu exporte une version préfixée.

**Comment by Jean-BaptisteC** [comment]
A fermer ?

**Comment by laem** [comment]
Carrément ! On n'est pas à l'abri d'autres problèmes, mais plus celui-ci :)
